name: kladml
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alembic=1.18.1
  - alsa-lib=1.2.15.3
  - aom=3.9.1
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - blas=2.137
  - blas-devel=3.9.0
  - bottle=0.13.4
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colorlog=6.10.1
  - contourpy=1.3.3
  - cpython=3.11.14
  - cuda-cudart=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.4.0
  - ffmpeg=2.8.6
  - filelock=3.20.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fsspec=2026.1.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.6
  - graphite2=1.3.14
  - greenlet=3.3.1
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - kaldi=5.5.1112
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.5
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurl=8.18.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libde265=1.0.15
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libheif=1.19.7
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=23.0.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.21.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.7.1
  - libunistring=0.9.10
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvpx=1.11.0
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - mako=1.3.10
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mkl=2024.2.2
  - mkl-devel=2024.2.2
  - mkl-include=2024.2.2
  - ml_dtypes=0.5.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - numpy=2.4.1
  - ocl-icd=2.3.3
  - onnx=1.20.0
  - onnxruntime=1.22.2
  - opencl-headers=2025.06.13
  - openfst=1.8.3
  - openh264=2.3.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.6.0
  - optree=0.18.0
  - optuna=4.7.0
  - optuna-dashboard=0.20.0
  - orc=2.2.2
  - packaging=26.0
  - pandas=3.0.0
  - patsy=1.0.2
  - pcre2=10.47
  - pillow=11.0.0
  - pip=25.3
  - pixman=0.46.4
  - polars=1.37.1
  - polars-runtime-32=1.37.1
  - prometheus-cpp=1.3.0
  - protobuf=6.31.1
  - pthread-stubs=0.4
  - pyarrow=23.0.0
  - pyarrow-core=23.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pyparsing=3.3.2
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.9.23
  - python-gil=3.11.14
  - python_abi=3.11
  - pytorch=2.7.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt6-main=6.10.1
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - s2n=1.6.2
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.10.1
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sqlalchemy=2.0.46
  - statsmodels=0.14.6
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.7.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.4.0
  - torchaudio=2.7.1
  - torchmetrics=1.8.2
  - torchtriton=3.1.0
  - torchvision=0.24.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.46.3
  - x264=1!161.3030
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - Flask==3.1.2
    - GitPython==3.1.46
    - Markdown==3.10.1
    - Pygments==2.19.2
    - SecretStorage==3.5.0
    - Werkzeug==3.1.5
    - accelerate==1.12.0
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.12.1
    - backports.tarfile==1.2.0
    - blinker==1.9.0
    - build==1.4.0
    - cachetools==5.5.2
    - click==8.3.1
    - cloudpickle==3.1.2
    - coverage==7.13.2
    - cryptography==46.0.3
    - databricks-sdk==0.80.0
    - docker==7.1.0
    - docutils==0.22.4
    - fastapi==0.128.0
    - gitdb==4.0.12
    - google-auth==2.48.0
    - graphene==3.4.3
    - graphql-core==3.2.7
    - graphql-relay==3.2.0
    - gunicorn==23.0.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.3.4
    - id==1.5.0
    - importlib_metadata==8.7.1
    - iniconfig==2.3.0
    - itsdangerous==2.2.0
    - jaraco.classes==3.4.0
    - jaraco.context==6.1.0
    - jaraco.functools==4.4.0
    - jeepney==0.9.0
    - keyring==25.7.0
    - kladml==0.10.2.dev14+gf82c5038d
    - loguru==0.7.3
    - markdown-it-py==4.0.0
    - mdurl==0.1.2
    - mlflow==2.22.4
    - mlflow-skinny==2.22.4
    - more-itertools==10.8.0
    - nh3==0.3.2
    - opentelemetry-api==1.39.1
    - opentelemetry-sdk==1.39.1
    - opentelemetry-semantic-conventions==0.60b1
    - packaging==24.2
    - platformdirs==4.5.1
    - pluggy==1.6.0
    - protobuf==6.33.4
    - psutil==7.2.1
    - pyarrow==19.0.1
    - pyasn1==0.6.2
    - pyasn1_modules==0.4.2
    - pydantic==2.12.5
    - pydantic-settings==2.12.0
    - pydantic_core==2.41.5
    - pyproject_hooks==1.2.0
    - pytest==9.0.2
    - pytest-cov==7.0.0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - readme_renderer==44.0
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==14.3.1
    - rsa==4.9.1
    - ruff==0.14.14
    - safetensors==0.7.0
    - shellingham==1.5.4
    - smmap==5.0.2
    - sqlmodel==0.0.31
    - sqlparse==0.5.5
    - starlette==0.50.0
    - sympy==1.13.1
    - twine==6.2.0
    - typer==0.21.1
    - typer-slim==0.21.1
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - uvicorn==0.40.0

prefix: "/home/marcello/miniforge3/envs/kladml"
