name: kladml
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpython=3.11.14
  - cuda-cudart=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - ffmpeg=4.4.0
  - filelock=3.20.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - jinja2=3.1.6
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.6.0
  - libuuid=2.41.3
  - libvpx=1.11.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.6.1
  - numpy=2.4.1
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=26.0
  - pillow=10.3.0
  - pip=25.3
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.10.1
  - sympy=1.14.0
  - tbb=2021.7.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.5.0
  - wheel=0.46.3
  - x264=1!161.3030
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - Flask==3.1.2
    - GitPython==3.1.46
    - Mako==1.3.10
    - Markdown==3.10.1
    - Pygments==2.19.2
    - SQLAlchemy==2.0.46
    - SecretStorage==3.5.0
    - Werkzeug==3.1.5
    - accelerate==1.12.0
    - alembic==1.18.1
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.12.1
    - backports.tarfile==1.2.0
    - blinker==1.9.0
    - build==1.4.0
    - cachetools==5.5.2
    - click==8.3.1
    - cloudpickle==3.1.2
    - contourpy==1.3.3
    - coverage==7.13.2
    - cryptography==46.0.3
    - cycler==0.12.1
    - databricks-sdk==0.80.0
    - docker==7.1.0
    - docutils==0.22.4
    - fastapi==0.128.0
    - fonttools==4.61.1
    - fsspec==2026.1.0
    - gitdb==4.0.12
    - google-auth==2.48.0
    - graphene==3.4.3
    - graphql-core==3.2.7
    - graphql-relay==3.2.0
    - greenlet==3.3.1
    - gunicorn==23.0.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.3.4
    - id==1.5.0
    - importlib_metadata==8.7.1
    - iniconfig==2.3.0
    - itsdangerous==2.2.0
    - jaraco.classes==3.4.0
    - jaraco.context==6.1.0
    - jaraco.functools==4.4.0
    - jeepney==0.9.0
    - joblib==1.5.3
    - keyring==25.7.0
    - kiwisolver==1.4.9
    - kladml==0.10.2.dev14+gf82c5038d
    - loguru==0.7.3
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mdurl==0.1.2
    - mlflow==2.22.4
    - mlflow-skinny==2.22.4
    - more-itertools==10.8.0
    - nh3==0.3.2
    - opentelemetry-api==1.39.1
    - opentelemetry-sdk==1.39.1
    - opentelemetry-semantic-conventions==0.60b1
    - packaging==24.2
    - pandas==2.3.3
    - platformdirs==4.5.1
    - pluggy==1.6.0
    - protobuf==6.33.4
    - psutil==7.2.1
    - pyarrow==19.0.1
    - pyasn1==0.6.2
    - pyasn1_modules==0.4.2
    - pydantic==2.12.5
    - pydantic-settings==2.12.0
    - pydantic_core==2.41.5
    - pyparsing==3.3.2
    - pyproject_hooks==1.2.0
    - pytest==9.0.2
    - pytest-cov==7.0.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - readme_renderer==44.0
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==14.3.1
    - rsa==4.9.1
    - ruff==0.14.14
    - safetensors==0.7.0
    - scikit-learn==1.8.0
    - scipy==1.17.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sqlmodel==0.0.31
    - sqlparse==0.5.5
    - starlette==0.50.0
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - twine==6.2.0
    - typer==0.21.1
    - typer-slim==0.21.1
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - uvicorn==0.40.0
    - zipp==3.23.0

prefix: "/home/marcello/miniforge3/envs/kladml"
